# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Google Analytics
google_analytics: UA—178277270-1

# Personal info
name: Dean Van Heukelom
title: Software Engineering Student
email: vanheukelomdean@gmail.com

# Social links
# twitter_username: facespics
github_username:  vanheukelomdean
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
linkedin_username: deanvanheukelom
# pinterest_username: jekyll
youtube_username: 
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Dean and I'm a student enrolled in Software Engineering at McMaster University. I am currently entering into the level 4 of 5 in my program after returning from completing 16 months of internships. I am most interested in deep learning, computer vision. sensor fusion and robotics.
  <br><br>
  <mark>C++</mark>
  <mark>Python</mark>
  <mark>Java</mark>
  <mark>JavaScript</mark>
  <mark>php</mark>


# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Besides Software Engineering, some of my other interests and hobbies are:
   - Sports (Hockey, Basketball, Soccer)
   - Weight Lifting
   - Music
   - Movies

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
